<!-- 摄像头相关的 xacro 文件 -->
<robot name="my_camera" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 摄像头属性 -->
    <xacro:property name="camera_length" value="0.1" /> <!-- 摄像头长度(x) -->
    <xacro:property name="camera_width" value="0.25" /> <!-- 摄像头宽度(y) -->
    <xacro:property name="camera_height" value="0.25" /> <!-- 摄像头高度(z) -->
    <xacro:property name="camera_mass" value="0.1" />
    <xacro:property name="camera_x" value="0.8" /> <!-- 摄像头安装的x坐标 -->
    <xacro:property name="camera_y" value="0.0" /> <!-- 摄像头安装的y坐标 -->
    <xacro:property name="camera_z" value="${base_link_length / 2 + camera_height / 2}" /> <!-- 摄像头安装的z坐标:底盘高度 / 2 + 摄像头高度 / 2  -->

    <!-- 摄像头关节以及link -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black">
                <color rgba="0.0 0.0 0.0 0.7" />
            </material>
        </visual>

        <collision>
                <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <!-- 调用惯性矩阵函数 -->
        <xacro:include filename="head.xacro" />
        <!-- m l w h 传参 -->
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}"/>
    </link>
    <!-- 在 <link>标签中找name-->
        <gazebo reference="camera">  
            <material>Gazebo/Blue</material>
        </gazebo>

    <joint name="camera2base" type="fixed">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${camera_x} ${camera_y} ${camera_z}" />
    </joint>
</robot>
